sculpin_content_types:
    posts:
        permalink: logs/:year/:month/:day/:filename/

sculpin_twig:
    source_view_paths:
        - _views
        - _layouts
        - _partials
        - _includes
# To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
#sculpin_content_types:
#    posts:
#        enabled: false
