# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Luston's dope website
subtitle: Hey! check out this cool website !
url: https://luston.neocities.org
# Insert your disqus shortname
disqus:
    shortname: luston-neocities-org

# Do not remove/edit
version:
    #{version}
